platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!

install! 'cocoapods', :disable_input_output_paths => true

target 'ProviderSelection' do
	pod 'Down', '~> 0.8.1'
	pod 'TinkLinkSDK', :path => '../../', :testspecs => ['Tests'] 
end

post_install do | installer |
  require 'fileutils'
  FileUtils.cp_r('Pods/Target Support Files/Pods-ProviderSelection/Pods-ProviderSelection-acknowledgements.plist', 'ProviderSelection/Settings.bundle/Acknowledgements.plist', :remove_destination => true)
end
