type_name:
  min_length: 4
  max_length:
    warning: 100
    error: 100
disabled_rules:
  - identifier_name
  - line_length
opt_in_rules:
  - overridden_super_call
  - prohibited_super_call
  - anyobject_protocol
  - empty_count
  - contains_over_first_not_nil
  - first_where
  - operator_usage_whitespace
  - redundant_type_annotation
  - toggle_bool
excluded:
  - Sources/TinkLink/GRPC
  - .build
  - Carthage
  - Examples/*/Pods
 